/*
******************************************************************
Copyright (c) 2017, Thiago Medeiros de Menezes
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are not permitted without specific prior written
permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
******************************************************************
*/

DROP DATABASE IF EXISTS NEWSLETTER2GO;
CREATE DATABASE NEWSLETTER2GO CHARACTER SET utf8 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT COLLATE utf8_unicode_ci;
DROP USER IF EXISTS 'newsletter2go'@'localhost';
DROP USER IF EXISTS 'newsletter2go'@'%';
CREATE USER 'newsletter2go'@'localhost' IDENTIFIED BY '3u_f4l0_4lem@0';
CREATE USER 'newsletter2go'@'%' IDENTIFIED BY '3u_f4l0_4lem@0';
GRANT ALL ON NEWSLETTER2GO.* TO 'newsletter2go'@'localhost' WITH GRANT OPTION;
GRANT ALL ON NEWSLETTER2GO.* TO 'newsletter2go'@'%' WITH GRANT OPTION;

USE NEWSLETTER2GO;

CREATE TABLE Recipient (
	recipient_id INT UNSIGNED AUTO_INCREMENT,
	recipient VARCHAR (64),
	email VARCHAR (255),
	PRIMARY KEY (recipient_id),
	UNIQUE (email)
) ENGINE = InnoDB;

CREATE TABLE SpecialOffer (
	offer_id INT UNSIGNED AUTO_INCREMENT,
	offer VARCHAR (64),
	discount FLOAT,
	PRIMARY KEY (offer_id)
) ENGINE = InnoDB;

CREATE TABLE VoucherCode (
	voucher_id INT UNSIGNED AUTO_INCREMENT,
	offer_id INT UNSIGNED,
	recipient_id INT UNSIGNED,
	code CHAR (8) NOT NULL,
	expiration_date DATE,
	used_date DATE,
	PRIMARY KEY (voucher_id),
	FOREIGN KEY (offer_id) REFERENCES SpecialOffer(offer_id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (recipient_id) REFERENCES Recipient(recipient_id) ON DELETE CASCADE ON UPDATE CASCADE,
	UNIQUE (code)
) ENGINE = InnoDB;
